from pathlib import Path
import json, html

root=Path(__file__).resolve().parents[1]
page=root/'dist/index.html'
original=page.read_text(encoding='utf-8')
prefix=original.split('<section class="p-about')[0] if '<section class="p-about' in original else original.split('  <section class="experience section"')[0]
prefix=prefix.replace('<link rel="stylesheet" href="ugc.css">','<link rel="stylesheet" href="portfolio.css">')
prefix=prefix.replace('content="Bhumi Kapoor — Data Science Engineer and CSE (AIML) undergraduate at Chandigarh University. Data science, machine learning, research and analytics."','content="Bhumi Kapoor — AI researcher, builder and founder. Explore Samsung PRISM research, technology projects, awards and work across AI, automation and business."')
LI='https://www.linkedin.com/in/bhumikapoor/'
MAIL='Bhumikapoor2005@gmail.com'
def img(src,alt,cls=''):
    return f'<img class="{cls}" src="assets/{src}" alt="{html.escape(alt)}" loading="lazy" decoding="async">'
def tag(s): return f'<span>{html.escape(s)}</span>'
def head(n,title,desc=''):
    return f'<div class="p-heading"><p class="p-kicker">{n}</p><div><h2>{title}</h2>{f"<p>{desc}</p>" if desc else ""}</div></div>'

about=f'''
<section class="p-about p-light" id="about-me" aria-labelledby="about-title">
 <div class="about-lead"><p class="p-kicker">01 — About me</p><h2 id="about-title">I don’t believe<br>in having just<br><em>one title.</em></h2><div class="role-list"><span>Researcher & builder</span><span>Problem-solver & communicator</span><span>Founder & lifelong learner</span></div><a class="text-link" href="#my-story">Meet the person behind the work ↘</a></div>
 <div class="photo-deck" tabindex="0" role="region" aria-label="Bhumi’s photo gallery. Use the arrow keys to change photos.">
   <div class="photo-back back-one"></div><div class="photo-back back-two"></div>
   <figure class="deck-slide active">{img('bhumi-portrait.png','Bhumi Kapoor in a black blazer')}<figcaption>Curious by nature. A builder by choice.</figcaption></figure>
   <figure class="deck-slide">{img('ingenium-team.jpg','Bhumi and her teammate with the ThinkLab Ideathon trophy')}<figcaption>Ideas become better when we build together.</figcaption></figure>
   <figure class="deck-slide">{img('achiever-2025.jpg','Bhumi receiving an Academic Achiever award')}<figcaption>Learning, growing, showing up.</figcaption></figure>
   <div class="deck-controls"><button aria-label="Previous photo">←</button><span id="photo-count" aria-live="polite">01 / 03</span><button aria-label="Next photo">→</button></div>
 </div>
 <div class="about-aside"><a class="mini-feature" href="#achievements">{img('extempore.jpg','Bhumi receiving the Extempore Award')}<div><small>A moment to remember</small><strong>Finding my voice.<br>Making an impact.</strong></div><span>↗</span></a><div class="about-note"><span class="handwritten">Always more<br>to explore.</span><p>I’m Bhumi Kapoor — a technology enthusiast, researcher, builder, problem-solver, communicator, and now, a founder.</p><a class="round-link" href="#contact">Let’s build something <b>↗</b></a></div></div>
 <svg class="about-wave" viewBox="0 0 1500 280" aria-hidden="true"><path id="about-wave-path" d="M-50 150 C270 440 650 15 880 120 S1240 -50 1580 130"/><text><textPath href="#about-wave-path">AI RESEARCH · AUTOMATION · DIGITAL PRODUCTS · FOUNDER · PROBLEM SOLVING · AI RESEARCH · AUTOMATION · DIGITAL PRODUCTS ·</textPath></text></svg>
</section>
<section class="p-story p-section" id="my-story"><p class="p-kicker">Beyond the job title</p><div><h2>Give me a problem.<br><span>I’ll move it forward.</span></h2><p>I’ve been working since my 10th standard. My biggest strength has never been one particular skill — it’s adapting, learning quickly, understanding the problem, and figuring out how to get the work done.</p><p>From AI research and machine learning to automation, websites, business analysis and client management, I’ve worked across very different spaces. Today, I’m bringing those experiences together as the founder of a technology venture, building practical digital solutions for businesses.</p><details class="story-more"><summary>More about my journey <span>＋</span></summary><p>I enjoy the thinking that happens before a solution is built: listening to what a client actually needs, breaking a problem down, finding the right approach, and turning an idea into something useful.</p><p>Alongside my venture, I’m working on AI and automation through a professional internship. I’ve mentored students, led technical projects, worked in international customer-facing environments, and learned how much good communication matters.</p><p>I’m curious by nature. I love learning and taking responsibility, even outside my comfort zone. Give me something worth solving, and I’ll learn what I need to learn to solve it.</p></details><div class="story-stats"><div><strong>35+</strong><span>Clients across the globe</span></div><div><strong>3</strong><span>Samsung PRISM worklets led</span></div><div><strong>8.8</strong><span>CGPA · CSE / AI & ML</span></div></div></div></section>
'''
experiences=[
('Technology & automation venture','Founder','Building globally','Bringing together a team to build websites, AI chatbots, agents and workflow systems. My role connects product thinking, business development, client communication and technical execution.','Entrepreneurship · AI automation · Digital products'),
('AI & automation','Current internship','Current','Exploring intelligent workflows and practical automation: understanding business requirements, experimenting with AI systems and simplifying repetitive processes.','AI · Automation · Business processes'),
('Samsung R&D Institute, Bangalore','AI Research Intern / Team Lead','Apr 2025 — Feb 2026','Led three Samsung PRISM worklets across Hindi, Urdu and Punjabi. Worked on spoken language identification, physical-access speaker-spoofed parallel databases, data preparation and model evaluation. Coordinated research, teammates and delivery.','Speech AI · NLP · Dataset development · Leadership'),
('C&B FREELANCERS','Business Development Executive','Feb — Apr 2026','Generated leads, understood client requirements and coordinated project conversations and follow-ups. Built experience translating business needs into practical solutions.','Business development · Client solutions'),
('Indulge Insights','Python & AI/ML Tutor / Instructor','Jan — Apr 2026','Delivered training in Python and machine learning, with practical coding exercises, project guidance and problem-solving sessions for students.','Python · Machine learning · Mentoring'),
('Teen Show Agency / STUSHE','Operational Lead / Full-Time Manager','2021 onward / 2024 onward','Operational leadership at Teen Show Agency and management work at STUSHE, bringing together coordination, ownership and client-facing execution. Dates reflect the supplied résumé.','Operations · Management · Communication'),
('Bogart / Artastherapyy','Social Media Manager / Graphic Designer','2020 — 2024','Worked across social media, graphic design, digital strategy and customer communication. Additional creative roles include Wizcraft Publication, LVL99, FIAN and HiFlyer.','Design · Content · Social media'),
('NIKKI.k · Picaro · Sol + Sonder','Marketing, support & international internships','2022 — 2024','Junior marketing at NIKKI.k, customer support at Picaro, an international brand internship at Sol + Sonder and a healthcare internship at Ivyleague. Each role strengthened my ability to listen, adapt and deliver.','Customer experience · Marketing · International work')]
experience='<section class="p-experience p-section" id="experience">'+head('02 — Experience','More than job titles.<br>A collection of things<br><em>I’ve built, learned & led.</em>','Technology taught me to build. Research taught me to question. Client-facing work taught me to listen and deliver.')+'<a class="small-pill cv-download" href="assets/bhumi-kapoor-resume.pdf" download>↓ Download CV</a><div class="experience-table">'
for company,role,date,desc,skills in experiences:
    experience+=f'<details class="experience-row"><summary><strong>{company}</strong><span>{role}</span><time>{date}</time><b>＋</b></summary><div class="experience-detail"><p>{desc}</p><small>{skills}</small></div></details>'
experience+='</div></section>'

projects=[
 dict(id='virtual-labs',name='Virtual Simulation Labs',category='AI / ML',image='virtual-labs.svg',label='Featured concept · EdTech AI',summary='Turning a natural-language prompt into a guided, interactive STEM simulation.',detail='A featured product concept for interactive STEM labs: a learner describes an experiment in natural language, the system maps the prompt to simulation parameters, and a guided interface presents live feedback. This concept card was added at the portfolio owner’s request; implementation details and project status should be confirmed before presenting it as shipped work.',tools=['NLP','Prompt-to-parameters','Interactive STEM'],note='Original interface concept illustration created for this portfolio; no external product screenshot is used.'),
 dict(id='drivesense',name='DriveSense',category='AI / ML',image='night-code.jpg',label='Funded startup',summary='Turning an ambitious mobility idea into an incubated venture.',detail='DriveSense won first place at TECH FUTURE 4.0 and received a ₹6.5 lakh startup grant from IIT Delhi and Delhi Incubator, according to the supplied résumé. This project represents a journey from an idea to a funded startup initiative.',tools=['Startup','Innovation','Mobility'],note='Editorial technology image; not a product screenshot.'),
 dict(id='ingenium',name='Ingenium',category='Products',image='ingenium-team.jpg',label='EdTech venture',summary='Learning beyond the classroom. Built with purpose.',detail='Ingenium is an education startup incubated with the University of Sydney and TBI Chandigarh University, and deployed in multiple schools according to the résumé. The team secured first prize at ThinkLab Ideathon 2025. Bhumi’s LinkedIn posts document the team and award.',tools=['EdTech','Product thinking','Teamwork'],note='ThinkLab Ideathon team photo from Bhumi’s LinkedIn activity.'),
 dict(id='speech',name='Spoken Language Identification',category='AI / ML',image='samsung.jpg',label='Samsung PRISM',summary='Making speech AI more robust across three languages.',detail='As a Samsung PRISM intern and team leader, Bhumi contributed to three worklets covering Hindi, Urdu and Punjabi. The research focused on improving spoken Language Identification robustness using physical-access speaker-spoofed parallel databases, supported by data preparation, experimentation and evaluation.',tools=['NLP','Speech AI','Dataset development'],note='Samsung PRISM certificate shared on LinkedIn.'),
 dict(id='tele',name='Tele-Automobile System',category='Research',image='coding.jpg',label='Award-winning research',summary='Exploring connected systems through WSN and MATLAB.',detail='Research on a real-time Tele-Automobile System using Wireless Sensor Networks and MATLAB. Listed as a research publication in the résumé and awarded first place in a research paper competition. Full publication metadata and the manuscript can be requested directly.',tools=['WSN','MATLAB','Simulation'],note='Editorial programming image; not a prototype photograph.'),
 dict(id='epi',name='Mathematical Modelling in Epidemiology',category='Research',image='workspace.jpg',label='Research publication',summary='Using mathematical thinking to explore human impact.',detail='A research publication listed in Bhumi’s résumé. The work concerns mathematical modelling in epidemiology. The manuscript, methods, publication venue and results are available on request; no unverified performance figures are presented here.',tools=['Mathematical models','Research','Analytics'],note='Editorial research workspace image.'),
 dict(id='automation',name='Intelligent business workflows',category='Automation',image='night-code.jpg',label='Current focus',summary='Helping businesses work smarter with AI and automation.',detail='Current work through Bhumi’s technology venture and professional internship explores AI chatbots, AI agents, websites and workflow automation. The focus is understanding business requirements and converting repetitive processes into practical digital systems.',tools=['AI agents','Automation','Web development'],note='Editorial technology image; client work is discussed privately.')]
projects[1]['detail']='DriveSense won first place at TECH FUTURE 4.0 and received a ₹6.5 lakh startup grant from IIT Delhi and Delhi Incubator. It is a startup initiative built around bringing an ambitious mobility idea from concept into an incubated venture.'
projects[2]['detail']='Ingenium is an education startup incubated with the University of Sydney and TBI Chandigarh University, with deployment in multiple schools. The team secured first prize at ThinkLab Ideathon 2025. The venture brings together product thinking, education and collaborative problem-solving.'
projects[4]['detail']='Research on a real-time Tele-Automobile System using Wireless Sensor Networks and MATLAB. The work received first place in a research paper competition, exploring how connected systems and simulation can address practical engineering questions. Get in touch to discuss the research or request publication details.'
projects[5]['detail']='This research explores mathematical modelling in epidemiology, connecting analytical thinking with questions about human impact. Get in touch to discuss the work and request the publication details.'
projects[1]['image']='mobility.jpg'
projects[1]['note']='Editorial mobility photograph by Hayden Sack / Unsplash; not a DriveSense prototype.'
featured='<section class="p-featured p-section p-light" id="projects">'+head('03 — Selected work','Ideas with<br><em>somewhere to go.</em>','A closer look at the ventures that bring research, people and product thinking together.')+'<div class="featured-grid">'
for i,p in enumerate(projects[:3]):
    featured+=f'<button class="feature-card{" feature-wide" if i==0 else ""}" data-project="{p["id"]}" aria-label="Explore {p["name"]}">{img(p["image"],p["note"])}<span class="feature-top">{p["label"]}<b>↗</b></span><span class="feature-bottom"><strong>{p["name"]}</strong><span class="p-tags">'+''.join(tag(t) for t in p['tools'])+'</span></span></button>'
featured+='</div></section>'
catalog='<section class="p-projects p-section" id="all-projects"><div class="catalog-heading"><div><p class="p-kicker">04 — The project shelf</p><h2>My projects<span>.</span></h2></div><div class="shelf-controls"><button aria-label="Scroll projects left">←</button><button aria-label="Scroll projects right">→</button></div></div><div class="project-filters" role="group" aria-label="Filter projects">'+''.join(f'<button data-filter="{s}" aria-pressed="{str(i==0).lower()}">{s}</button>' for i,s in enumerate(['All','AI / ML','Products','Research','Automation']))+'</div><div class="project-shelf" tabindex="0" aria-label="Project cards">'
for p in projects:
    catalog+=f'<article class="project-tile" data-category="{p["category"]}"><button data-project="{p["id"]}">{img(p["image"],p["note"])}<span class="tile-category">{p["label"]} <b>↗</b></span><h3>{p["name"]}</h3><p>{p["summary"]}</p><span class="p-tags">'+''.join(tag(t) for t in p['tools'])+'</span></button></article>'
catalog+='</div><p class="shelf-hint">Explore a card for the story behind the work. <span id="project-count" aria-live="polite">7 projects</span></p></section>'

awards=[('01','Exemplary Achiever','Chandigarh University · 2026','Recognised in April 2026 for continued growth and achievement.'),('02','Academic Achiever','Chandigarh University · 2025','A second consecutive year of recognition across the 2025–2026 journey.'),('03','1st place · TECH FUTURE 4.0','₹6.5 lakh startup grant','DriveSense — IIT Delhi & Delhi Incubator.'),('04','Finalist · ROBOFEST 4.0','₹2.5 lakh award','Gujarat government support in the Underwater Submarine category.'),('05','1st place · ThinkLab Ideathon','Ingenium · 2025','An EdTech idea brought to life with Prabhmannat Singh and Arnav Hooda.'),('06','Two gold medals','Chandigarh University · 2026','Recognised for internships, practical learning, certifications and extracurricular involvement.'),('07','Extempore Award','Communication & public speaking','Recognition from Chandigarh University leadership.'),('08','Research & innovation honours','Competitions & university events','1st in the Tele-Automobile research paper competition; 3rd at Thapar’s Innovation Hackathon; recognised by SRM for hosting IEEE Final HIZE.')]
achievements='<section class="p-achievements p-section" id="achievements">'+head('05 — Achievements & awards','Small moments.<br><em>Meaningful milestones.</em>','Recognition is a reminder to keep learning — and to bring others along.')+'<div class="memory-board" aria-label="Draggable achievement photo board"><div class="board-slots" aria-hidden="true">▯ ▯ ▯ ▯ ▯ ▯ ▯</div>'
for i,(src,label) in enumerate([('achiever-2025.jpg','Academic Achiever · 2025'),('extempore.jpg','Finding my voice'),('ingenium-team.jpg','ThinkLab · 1st prize'),('achiever-2026.jpg','Exemplary Achiever · 2026')]):
    achievements+=f'<button class="memory" style="--i:{i};--rotation:{[-9,5,-4,8][i]}deg" aria-label="Move photo: {label}. Use arrow keys.">{img(src,label)}<span>{label}</span></button>'
achievements+='<p>Drag the photos to rearrange <span>·</span> or focus a photo and use arrow keys <button id="reset-memories">Reset ↺</button></p></div><div class="awards-grid">'
for num,title,sub,desc in awards:
    achievements+=f'<article><small>{num}</small><div><h3>{title}</h3><span>{sub}</span><p>{desc}</p></div></article>'
achievements+=f'</div><a class="text-link" href="{LI}recent-activity/all/" target="_blank" rel="noreferrer">More moments on LinkedIn ↗</a></section>'

certs=[('AI','Artificial Intelligence Analyst','Chandigarh University · April 2026','https://courses.cu.skillsnetwork.site/certificates/0d5ad49e215c4ab4921537ca9a7f7b9b'),('M','Introduction to Programming with MATLAB','Vanderbilt University · April 2026','https://www.coursera.org/account/accomplishments/verify/P9ZEO2KBMLEW'),('S','Samsung PRISM Program','Certificate of participation · 2025–2026','assets/samsung.jpg'),('▦','Discover data analysis','Microsoft Learn · Learning badge',LI+'recent-activity/all/')]
certifications='<section class="p-certifications p-section" id="certifications">'+head('06 — Certifications','Still learning.<br><em>Always will be.</em>')+'<div class="cert-grid">'
for logo,title,issuer,url in certs:
    certifications+=f'<a class="cert-card" href="{url}" target="_blank" rel="noreferrer"><span class="cert-logo">{logo}</span><span><h3>{title}</h3><p>{issuer}</p></span><b>↗</b></a>'
certifications+=f'</div><a class="text-link" href="{LI}details/certifications/" target="_blank" rel="noreferrer">View all credentials on LinkedIn ↗</a></section>'

research='<section class="p-research p-section p-light" id="research"><div class="p-heading p-heading-no-kicker"><div><h2>Questions.<br><em>Experiments. Insights.</em></h2><p>From speech AI to connected systems, a space for deeper thinking.</p></div></div><div class="research-grid">'
for pid in ['speech','tele','epi']:
    p=next(p for p in projects if p['id']==pid)
    research+=f'<article><button data-project="{pid}">{img(p["image"],p["note"])}<small>{"Industry research case study" if pid=="speech" else "Research publication"}</small><h3>{p["name"]}</h3><p>{p["summary"]}</p><span class="author">BK <span>Bhumi Kapoor</span><b>↗</b></span></button></article>'
research+='</div></section>'

testimonials=f'''<section class="p-testimonials p-section" id="testimonials">{head('08 — People & collaboration','Good work is<br><em>a team sport.</em>','The people beside the work matter just as much as the work itself.')}<div class="testimonial-grid"><article class="quote-slot"><span class="quote-mark">“</span><p>A space for words from<br>the people I build with.</p><div class="quote-author"><span class="initial-avatar">＋</span><div><strong>Fellow developer</strong><small>Testimonial awaiting an approved quote</small></div></div></article><figure class="team-photo">{img('ingenium-team.jpg','Bhumi and Prabhmannat with their ThinkLab trophy')}<figcaption>Different strengths.<br>Shared ambition.</figcaption></figure><div class="collaboration-notes"><div class="chat-bubble">Listen closely.</div><div class="chat-bubble">Build thoughtfully.</div><div class="chat-bubble lavender">Move it forward. ↗</div><a href="mailto:{MAIL}?subject=Portfolio%20testimonial">Worked together?<br><strong>Share your experience ↗</strong></a><small>Real feedback will appear here with the contributor’s permission.</small></div></div></section>'''

drafts=[
('Prabhmannat Singh','FDE · Big Tech, Sydney','Bhumi brings clarity to the messy part of building. She asks the right questions, connects the technical work to the bigger picture, and takes ownership of moving things forward.','Draft quote · awaiting approval'),
('Arnav','Frontend Developer · Webstell','Working with Bhumi feels collaborative from the start. She communicates her ideas clearly, listens to feedback, and keeps the team focused on making something genuinely useful.','Draft quote · awaiting approval'),
('Riya Mehta','Full-Stack Developer','From understanding the problem to working through the details, Bhumi brings curiosity and care to the process. She makes space for different perspectives and keeps learning as the work evolves.','Fictional example · sample persona')]
quote_cards=[]
for name,role,quote,status in drafts:
    quote_cards.append(f'<article class="testimonial-quote"><small class="quote-draft">{status}</small><span class="quote-mark">“</span><p>{quote}</p><div class="quote-author"><span class="initial-avatar" aria-label="Avatar placeholder">＋</span><div><strong>{name}</strong><small>{role}</small></div></div></article>')
testimonials=f'''<section class="p-testimonials p-section" id="testimonials">{head("08 — People & collaboration","Good work is<br><em>a team sport.</em>","The people beside the work matter just as much as the work itself.")}<p class="draft-note">Draft testimonials — sample wording for review, not approved endorsements.</p><div class="testimonial-collage">
<div class="tq-one">{quote_cards[0]}</div><figure class="testimonial-photo tp-main">{img("ingenium-team.jpg","Bhumi with her ThinkLab teammate")}<figcaption>Different strengths. Shared ambition.</figcaption></figure><div class="testimonial-chat"><p>how do you keep<br>so many ideas moving?</p><span>listen</span><span>learn</span><span class="lavender">build together</span></div><div class="tq-two">{quote_cards[1]}</div><figure class="testimonial-photo tp-side">{img("achiever-2026.jpg","Bhumi receiving an achievement award")}<figcaption>Learning. Leading. Growing.</figcaption></figure><div class="tq-three">{quote_cards[2]}</div></div><a class="text-link testimonial-invite" href="mailto:{MAIL}?subject=Portfolio%20testimonial">Worked together? Share your experience ↗</a></section>'''

contact=f'''<section class="p-contact-wrap p-section p-light" id="contact"><div class="hire-grid"><div class="hire-copy"><svg viewBox="0 0 400 120" aria-hidden="true"><path d="M-20 90 Q160 160 145 40 C120 -30 70 90 200 70 S350 70 420 -10"/></svg><p class="p-kicker">09 — Let’s work together</p><h2>Big ideas.<br>Better<br><em>together.</em></h2><p>Have a challenge worth solving? I’m open to AI, automation, research, product and business opportunities.</p><a class="round-link" href="#contact-form">Let’s talk <b>↗</b></a></div><div class="hire-photo">{img('industry.jpg','Bhumi with fellow attendees at a university industry event')}<span>Technology is powerful.<br>People make it matter.</span></div></div><div class="say-hi"><p class="p-kicker">Start a conversation</p><h2>Say <em>Hi</em> <span aria-hidden="true">👋</span></h2><p>Tell me about the problem, project or opportunity on your mind.</p></div><div class="contact-panel"><div class="contact-illustration" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="idea-star">✦</div><div class="laptop"><span></span></div><div class="contact-avatar">BK</div><p>Let’s make the idea<br><strong>real.</strong></p></div><form id="contact-form"><div class="contact-form-heading"><p class="p-kicker">Get in touch</p><h3>Fill out the form and I’ll get back to you soon.</h3></div><div class="form-row"><label>Your name<input name="name" required maxlength="100" autocomplete="name" placeholder="Name"></label><label>Email address<input name="email" required type="email" maxlength="150" autocomplete="email" placeholder="you@company.com"></label></div><label>What can we build together?<select name="interest"><option>AI & automation</option><option>Research collaboration</option><option>Websites & digital products</option><option>Internship / hiring opportunity</option><option>Something else</option></select></label><label>Your message<textarea name="message" required minlength="10" maxlength="4000" rows="4" placeholder="A little about your idea, project or opportunity…"></textarea></label><button class="send-button" type="submit">Create email draft <span>↗</span></button><p class="form-note" id="form-status" role="status">Opens your email app with a prepared message.</p></form></div><div class="contact-direct"><a href="mailto:{MAIL}">{MAIL} ↗</a><span>Amritsar, Punjab · Working globally</span><a href="{LI}" target="_blank" rel="noreferrer">Connect on LinkedIn ↗</a></div></section>
<footer class="p-footer"><div class="footer-media"><div class="spotify-shell"><div><small>Currently on repeat</small><strong>A track for the build</strong><a href="https://open.spotify.com/track/3hB9lDLyAClYVZivMMl20N" target="_blank" rel="noreferrer">Open in Spotify ↗</a></div><iframe title="Bhumi’s featured Spotify track" src="https://open.spotify.com/embed/track/3hB9lDLyAClYVZivMMl20N?utm_source=generator&amp;theme=0" width="100%" height="152" loading="lazy" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe></div><div class="footer-photos">{img('achiever-2025.jpg','Bhumi at an academic achievement ceremony')}{img('extempore.jpg','Bhumi receiving an extempore award')}</div></div><div class="footer-socials" aria-label="Social links"><a href="{LI}" target="_blank" rel="noreferrer">in LinkedIn</a><a href="https://github.com/PRABHMANNAT/Bhumi-didi-portfolio" target="_blank" rel="noreferrer">⌘ Portfolio GitHub</a><a href="mailto:{MAIL}">✉ Email</a><span class="is-disabled" title="Instagram link to be added">◎ Instagram · add link</span></div><div class="footer-marquee" aria-hidden="true"><div><span>✦ AI RESEARCH</span><span>◌ AUTOMATION</span><span>⌁ DIGITAL PRODUCTS</span><span>✦ BUILT WITH CURIOSITY</span><span>✦ AI RESEARCH</span><span>◌ AUTOMATION</span><span>⌁ DIGITAL PRODUCTS</span><span>✦ BUILT WITH CURIOSITY</span></div></div><div class="footer-top"><a class="logo" href="#" aria-label="Bhumi Kapoor home">BK<sup>®</sup></a><p>Curiosity. Ownership. Impact.</p><nav aria-label="Footer navigation"><a href="#about-me">About</a><a href="#all-projects">Projects</a><a href="#research">Research</a><a href="{LI}" target="_blank" rel="noreferrer">LinkedIn ↗</a></nav></div><div class="footer-name" aria-hidden="true">BHUMI KAPOOR</div><div class="footer-bottom"><span>© <span id="year">2026</span> Bhumi Kapoor</span><a href="assets/bhumi-kapoor-resume.pdf" download>Download résumé ↓</a><a href="#">Back to top ↑</a></div></footer>
<dialog class="project-dialog" id="project-dialog" aria-labelledby="dialog-title"><button class="dialog-close" aria-label="Close project details">×</button><div id="dialog-content"></div></dialog>
'''
# Contact and footer changes are kept as focused substitutions so the original
# authoring template above stays intact while individual design choices are easy to revise.
contact=contact.replace('''<div class="say-hi"><p class="p-kicker">Start a conversation</p><h2>Say <em>Hi</em> <span aria-hidden="true">👋</span></h2><p>Tell me about the problem, project or opportunity on your mind.</p></div>''','')
contact=contact.replace('''<p>Let’s make the idea<br><strong>real.</strong></p>''','')
contact=contact.replace('''<div class="contact-avatar">BK</div>''','')
contact=contact.replace('''<div class="idea-star">✦</div>''','')
contact=contact.replace('''<div class="footer-socials" aria-label="Social links"><a href="{LI}" target="_blank" rel="noreferrer">in LinkedIn</a><a href="https://github.com/PRABHMANNAT/Bhumi-didi-portfolio" target="_blank" rel="noreferrer">⌘ Portfolio GitHub</a><a href="mailto:{MAIL}">✉ Email</a><span class="is-disabled" title="Instagram link to be added">◎ Instagram · add link</span></div>''','')
contact=contact.replace('''<div class="footer-top"><a class="logo" href="#" aria-label="Bhumi Kapoor home">BK<sup>®</sup></a><p>Curiosity. Ownership. Impact.</p><nav aria-label="Footer navigation"><a href="#about-me">About</a><a href="#all-projects">Projects</a><a href="#research">Research</a><a href="{LI}" target="_blank" rel="noreferrer">LinkedIn ↗</a></nav></div><div class="footer-name" aria-hidden="true">BHUMI KAPOOR</div>''','''<div class="footer-name" aria-hidden="true">BHUMI KAPOOR</div><div class="footer-top"><a class="logo" href="#" aria-label="Bhumi Kapoor home">BK<sup>®</sup></a><p>Curiosity. Ownership. Impact.</p><nav aria-label="Footer navigation"><a href="#about-me">About</a><a href="#all-projects">Projects</a><a href="#research">Research</a><a href="{LI}" target="_blank" rel="noreferrer">LinkedIn ↗</a></nav></div>''')
contact=contact.replace('''<p class="p-kicker">09 — Let’s work together</p>''','')
page.write_text(prefix+about+experience+featured+catalog+achievements+certifications+research+testimonials+contact+'\n</main><script src="script.js"></script><script src="portfolio.js"></script></body></html>\n',encoding='utf-8')
(root/'dist/project-data.json').write_text(json.dumps(projects,ensure_ascii=False,indent=2),encoding='utf-8')
script=(root/'dist/script.js').read_text(encoding='utf-8').split('const ugcSlides')[0]
(root/'dist/script.js').write_text(script.rstrip()+'\n',encoding='utf-8')
print('Portfolio sections generated. Hero and skills markup preserved.')
